version: "3"

tasks:
  _prepare:
    cmds:
      - pip install -r requirements.txt

  run:
    deps:
      - _prepare
    cmds:
      - python -m firome {{.CLI_ARGS}}

  generate:
    cmds:
      - pyside6-uic firome/ui/assets/main.ui -o firome/ui/main_ui.py

  ui:
    deps:
      - _prepare
    cmds:
      - python -m firome.ui

  build:
    deps:
      - _prepare
    preconditions:
      - pip install pyinstaller  # TODO: use tox or other dependency splitting
    cmds:
      - pyinstaller --onefile --windowed --name firome firome/ui/__main__.py

  lint:
    preconditions:
      - pip install ruff  # TODO: use tox or other dependency splitting
    cmds:
      - ruff check

  format:
    preconditions:
      - pip install ruff  # TODO: use tox or other dependency splitting
    cmds:
      - ruff format
