version: "3"

tasks:
  _prepare:
    cmds:
      - pip install -r requirements.txt

  run:
    deps:
      - _prepare
    cmds:
      - python -m firome {{.CLI_ARGS}}

  generate:
    cmds:
      - pyside6-uic firome/ui/assets/main.ui -o firome/ui/main_ui.py

  ui:
    deps:
      - _prepare
    cmds:
      - python -m firome.ui

  build:
    deps:
      - _prepare
    preconditions:
      - pip install pyinstaller # TODO: use tox or other dependency splitting
    cmds:
      - pyinstaller --onefile --console --name firome firome/__main__.py

  build-ui:
    deps:
      - _prepare
    preconditions:
      - pip install pyinstaller # TODO: use tox or other dependency splitting
    cmds:
      - pyinstaller --onefile --windowed --add-data "firome/i18n/assets/*.ini:firome/i18n/assets" --name firome-ui firome/ui/__main__.py

  build-all:
    cmds:
      - task: build
      - task: build-ui

  lint:
    preconditions:
      - pip install ruff # TODO: use tox or other dependency splitting
    cmds:
      - ruff check
      - pyright

  lint:fix:
    preconditions:
      - pip install ruff # TODO: use tox or other dependency splitting
    cmds:
      - ruff check --fix

  format:
    preconditions:
      - pip install ruff # TODO: use tox or other dependency splitting
    cmds:
      - ruff format
