name: Release

# todo: replace with `release`
on:
  push:
    branches:
      - release-upload

jobs:
  release:
    name: Release ${{ matrix.application.name }} ${{ matrix.os.name }} app
    runs-on: ${{ matrix.os.run }}
    strategy:
      matrix:
        os:
#          - run: ubuntu-latest
#            name: linux
          - run: windows-latest
            name: windows
#          - run: macos-latest
#            name: macos
        application:
          - name: ui
            path: firome/ui/__main__.py
            flag: --windowed
          - name: cli
            path: firome/__main__.py
            flag: --console
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Create venv
        run: python -m venv .venv
      - name: Install pyinstaller
        run: ./.venv/bin/pip install pyinstaller
      - name: Run pyinstaller
        run: ./.venv/bin/pyinstaller --onefile ${{ matrix.application.flag }} --name firome-${{ matrix.application.name }} ${{ matrix.application.path }}
      - name: Check binary
        run: ls -lAh ./dist
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/firome-${{ matrix.application.name }}
          name: ./dist/firome-${{ matrix.os.name }}-${{ matrix.application.name }}