name: Release

# todo: replace with `release`
on:
  push:
    branches:
      - release-upload

jobs:
  release:
    name: Release CLI and GUI apps
    runs-on: ${{ matrix.os.run }}
    strategy:
      matrix:
        os:
          - run: ubuntu-latest
            name: linux
#          - run: windows-latest
#            name: windows
#          - run: macos-latest
#            name: macos
        interface:
          - name: ui
            path: firome/ui/__main__.py
            flag: --windowed
          - name: cli
            path: firome/__main__.py
            flag: --console
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Create venv
        run: python -m venv .venv
      - name: Install pyinstaller
        run: ./.venv/bin/pip install pyinstaller
      - name: Run pyinstaller
        run: pyinstaller --onefile ${{ matrix.interface.flag }} --name firome-${{ matrix.interface.name }} ${{ matrix.interface.name.path }}
      - name: Check binary
        run: ls -lAh ./dist
